[tea-app-server]
server1 ansible_host="54.82.77.217"
server1 ansible_user="Ubuntu"
server2 ansible_host="34.207.78.210"
server2 ansible_host="ec2-user"
[tea-app-server:vars]
ansible-python-interpreter=/usr/bin/python3
ansible_ssh_private_key_file = /home/ubuntu/keys/ansible-terraform.pem
